---
title: "Genotype quality control with plinkQC"
author: "Hannah Meyer"
date: "`r Sys.Date()`"
output: 
    pdf_document:
        fig_caption: yes
        toc: true
        toc_depth: 2
vignette: >
  %\VignetteIndexEntry{GenotypeQC_with_plinkQC}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
devtools::load_all()
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r set parameters}
package.dir <- find.package('plinkQC')
qcdir <- "~/RPackagesDevel/plinkQC/inst/extdata"
#qcdir <- file.path(package.dir, 'extdata')
alg <- 'data'
path2plink <- "~/bin"
```

```{r run qc}

```

```{r sample QC,  fig.height=8, fig.width=6}
fail_samples <- perSampleQC(qcdir=qcdir, alg=alg,
                                #refSamplesFile=refSamplesFile, 
                                #refColorsFile=refColorsFile,
                                do.check_ancestry=FALSE,
                                prefixMergedDataset="data.HapMapIII.pruned.pca",
                                interactive=TRUE, verbose=TRUE)

```

```{r overview sample QC}
overview_samples <- overviewPerSampleQC(fail_samples, interactive=TRUE)
```

```{r marker QC, fig.height=8, fig.width=6}
fail_markers <- perMarkerQC(qcdir=qcdir, alg=alg, path2plink=path2plink,
                            verbose=TRUE, interactive=TRUE, showPlinkError=TRUE)
```


```{r overview marker QC}
overview_marker <- overviewPerMarkerQC(fail_markers, interactive=TRUE)
```

